MICOMPLETEDB:   'Bact105.hmm'
VOGDB:  'AllVOG.hmm'
cluster_project:  ''
tmpdir: 'mag_annotation_tmp'
contig_suffix:  '.fna'
threads_ppn:  '30'
combined_assembly:  'contigs.fna.gz'
vamb_directory:   'vamb'