MICOMPLETEDB:   '/home/projects/cpr_10006/projects/phamb/databases/miComplete/Bact105.hmm'
VOGDB:  '/home/projects/cpr_10006/projects/phamb/databases/VOG/vog_hmms/AllVOG.hmm'
cluster_project:  'cpr_10006'
tmpdir: 'mag_annotation_tmp'
contig_suffix:  '.fna'
threads_ppn:  '30'
combined_assembly:  'contigs.fna.gz'
vamb_directory:   'vamb'