MICOMPLETEDB:   '/home/projects/cpr_10006/projects/phamb/databases/miComplete/Bact105.hmm'
VOGDB:  '/home/projects/cpr_10006/projects/phamb/databases/VOG/vog_hmms/AllVOG.hmm'
sample_file_path:  ''
cluster_project:  'cpr_10006'
tmpdir: 'tmp'
contig_suffix:  '.flt.fna'
threads_ppn:  '30'
combined_assembly:  ''
vamb_directory:   ''